[package]
name = "radicle-tools"
version = "0.0.0"
edition = "2018"

[dependencies]
colored = { version = "1.9" }
atty = { version = "0.2" }
log = { version = "0.4", features = ["std"] }

[workspace]
members = [
  "anchor",
  "account",
  "safe-transaction-client",
  "proof-generator",
  "remote-helper",
]

[patch.crates-io.link-identities]
git = "https://github.com/radicle-dev/radicle-link"
branch = "master"

[patch.crates-io.librad]
git = "https://github.com/radicle-dev/radicle-link"
branch = "master"

[patch.crates-io.ethers]
git = "https://github.com/gakonst/ethers-rs"
branch = "master"

[patch.crates-io.thrussh-encoding]
git = "https://github.com/FintanH/thrussh.git"
branch = "generic-agent"
