[package]
name = "radicle-tools"
version = "0.0.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"

[package.metadata.deb]
assets = [
    ["target/release/rad-show", "usr/bin/rad-show", "755"],
    ["target/release/rad-account", "usr/bin/rad-account", "755"],
    ["target/release/rad-sync", "usr/bin/rad-sync", "755"],
    ["target/release/rad-help", "usr/bin/rad-help", "755"],
    ["target/release/rad-ens", "usr/bin/rad-ens", "755"],
    ["target/release/rad-push", "usr/bin/rad-push", "755"],
    ["target/release/rad", "usr/bin/rad", "755"],
    ["target/release/rad-auth", "usr/bin/rad-auth", "755"],
    ["target/release/rad-track", "usr/bin/rad-track", "755"],
    ["target/release/rad-ls", "usr/bin/rad-ls", "755"],
    ["target/release/rad-init", "usr/bin/rad-init", "755"],
    ["target/release/rad-clone", "usr/bin/rad-clone", "755"],
    ["target/release/rad-checkout", "usr/bin/rad-checkout", "755"],
    ["target/release/rad-untrack", "usr/bin/rad-untrack", "755"],
    ["target/release/rad-remote", "usr/bin/rad-remote", "755"],
    ["target/release/git-remote-rad", "usr/bin/git-remote-rad", "755"],
    ["radicle-tools.1.gz", "usr/share/man/man1/radicle-tools.1.gz", "644"],
]

[dependencies]
anyhow = "1.0"
lexopt = "0.2"
colored = { version = "1.9" }
atty = { version = "0.2" }
log = { version = "0.4", features = ["std"] }
librad = { version = "0" }
rad-exe = { version = "0" }
rad-profile = { version = "0" }
rad-clone = { path = "./clone" }
rad-account = { path = "./account" }
rad-auth = { path = "./auth" }
rad-common = { path = "./common" }
rad-terminal = { path = "./terminal" }
rad-init = { path = "./init" }
rad-show = { path = "./show" }
rad-push = { path = "./push" }
rad-sync = { path = "./sync" }
rad-remote = { path = "./remote" }
rad-ens = { path = "./ens" }
rad-checkout = { path = "./checkout" }
rad-track = { path = "./track" }
rad-untrack = { path = "./untrack" }
rad-help = { path = "./help" }
rad-ls = { path = "./ls" }
rad-rm = { path = "./rm" }
ethers = { version = "0.6.2" }
link-identities = { version = "0" }
radicle-git-helpers = { version = "0" }
url = { version = "*" }
tokio = { version = "1.10", features = ["rt"] }
futures = { version = "0.3" }

[workspace]
members = [
  "anchor",
  "account",
  "terminal",
  "common",
  "checkout",
  "ens",
  "auth",
  "help",
  "rad",
  "init",
  "ls",
  "rm",
  "push",
  "remote",
  "sync",
  "show",
  "track",
  "untrack"
]

[patch.crates-io.link-crypto]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-02-15"

[patch.crates-io.link-identities]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-02-15"

[patch.crates-io.radicle-git-helpers]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-02-15"

[patch.crates-io.librad]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-02-15"

[patch.crates-io.rad-clib]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-02-15"

[patch.crates-io.rad-profile]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-02-15"

[patch.crates-io.rad-exe]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-02-15"

[patch.crates-io.radicle-git-ext]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-02-15"

[patch.crates-io.rad-identities]
git = "https://github.com/radicle-dev/radicle-link"
tag = "cycle/2022-02-15"

[patch.crates-io.thrussh-encoding]
git = "https://github.com/FintanH/thrussh.git"
branch = "generic-agent"
