[package]
name = "rad-auth"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Manage radicle identities and profiles"

[dependencies]
anyhow = "1.0"
lexopt = "0.2.0"
rad-profile = "0"
rad-terminal = { path = "../terminal" }
rad-common = { path = "../common" }
